In [86]:
# Import

import pandas as pd

import hvplot.pandas

from pathlib import Path

In [87]:
# Using the read_csv function and Path module, create a DataFrame

#importing the sfo_neighborhoods_census_data.csv file

sfo_data_df = pd.read_csv('D:/git/UTOR-VIRT-FIN-PT-05-2022-U-LOLC/Resources/sfo_neighborhoods_census_data.csv')

# Review the first and last five rows of the DataFrame

sfo_data_df

,year,neighborhood,sale_price_sqr_foot,housing_units,gross_rent
0,2010,Alamo Square,291.182945,372560,1239
1,2010,Anza Vista,267.932583,372560,1239
2,2010,Bayview,170.098665,372560,1239
3,2010,Buena Vista Park,347.394919,372560,1239
4,2010,Central Richmond,319.027623,372560,1239
...,...,...,...,...,...
392,2016,Telegraph Hill,903.049771,384242,4390
393,2016,Twin Peaks,970.085470,384242,4390
394,2016,Van Ness/ Civic Center,552.602567,384242,4390
395,2016,Visitacion Valley,328.319007,384242,4390
396,2016,Westwood Park,631.195426,384242,4390

In [88]:
# Create a numerical aggregation that groups the data by the year and then averages the results.

housing_units_by_year = sfo_data_df.groupby("year").mean()

# Review the DataFrame

housing_units_by_year

      sale_price_sqr_foot  housing_units  gross_rent
year
2010           369.344353       372560.0      1239.0
2011           341.903429       374507.0      1530.0
2012           399.389968       376454.0      2324.0
2013           483.600304       378401.0      2971.0
2014           556.277273       380348.0      3528.0
2015           632.540352       382295.0      3739.0
2016           697.643709       384242.0      4390.0

In [89]:
# Use the hvplot function to plot the housing_units_by_year DataFrame as a bar chart

# Make the x-axis represent the year and the y-axis represent the housing_units

# Style and format the line plot to ensure a professionally styled visualisation

housing_units_by_year_plot = housing_units_by_year.hvplot.bar(x="year",y="housing_units",ylim=(365000, 385000),label="Housing units in San francisco from 2010 to 2016").opts(yformatter='%.0f').opts(xlabel='Year',ylabel='Housing Units')

housing_units_by_year_plot

:Bars   [year]   (housing_units)

In [90]:
# Calculate and Plot the Average Sale Prices per Square Foot

# Create a numerical aggregation by grouping the data by year and averaging the results

gross_rent = sfo_data_df.groupby("year").mean().sort_values("gross_rent",ascending=True)

# Review the resulting DataFrame

gross_rent

      sale_price_sqr_foot  housing_units  gross_rent
year
2010           369.344353       372560.0      1239.0
2011           341.903429       374507.0      1530.0
2012           399.389968       376454.0      2324.0
2013           483.600304       378401.0      2971.0
2014           556.277273       380348.0      3528.0
2015           632.540352       382295.0      3739.0
2016           697.643709       384242.0      4390.0

In [91]:
# Filter out the housing_units column, creating a new DataFrame 

# Keep only sale_price_sqr_foot and gross_rent averages per year

prices_square_foot_by_year = gross_rent[['sale_price_sqr_foot','gross_rent']]

# Review the DataFrame

prices_square_foot_by_year

      sale_price_sqr_foot  gross_rent
year
2010           369.344353      1239.0
2011           341.903429      1530.0
2012           399.389968      2324.0
2013           483.600304      2971.0
2014           556.277273      3528.0
2015           632.540352      3739.0
2016           697.643709      4390.0

In [92]:
# Use hvPlot to plot the prices_square_foot_by_year DataFrame as a line plot

# Style and format the line plot to ensure a professionally styled visualisation

prices_square_foot_by_year_plot = prices_square_foot_by_year.hvplot.line(x="year",y=["sale_price_sqr_foot","gross_rent"],label="Sale Price Per Square Foot and Average Gross Rent - 2010-2016 - San Francisco").opts(yformatter='%.0f',xlabel='Year',ylabel='Gross Rent/Sale Price Per Square Foot')

prices_square_foot_by_year_plot

:NdOverlay   [Variable]
   :Curve   [year]   (value)

In [93]:
# Group by year and neighborhood and then create a new dataframe of the mean values

prices_by_year_by_neighborhood = sfo_data_df.groupby(["year","neighborhood"]).mean()

# Review the DataFrame

prices_by_year_by_neighborhood

                             sale_price_sqr_foot  housing_units  gross_rent
year neighborhood
2010 Alamo Square                     291.182945       372560.0      1239.0
     Anza Vista                       267.932583       372560.0      1239.0
     Bayview                          170.098665       372560.0      1239.0
     Buena Vista Park                 347.394919       372560.0      1239.0
     Central Richmond                 319.027623       372560.0      1239.0
...                                          ...            ...         ...
2016 Telegraph Hill                   903.049771       384242.0      4390.0
     Twin Peaks                       970.085470       384242.0      4390.0
     Van Ness/ Civic Center           552.602567       384242.0      4390.0
     Visitacion Valley                328.319007       384242.0      4390.0
     Westwood Park                    631.195426       384242.0      4390.0

[397 rows x 3 columns]

In [94]:
 # Filter out the housing_units
    
prices_by_year_by_neighborhood_new = prices_by_year_by_neighborhood[['sale_price_sqr_foot','gross_rent']]

# Review the Dataframe

prices_by_year_by_neighborhood_new

                             sale_price_sqr_foot  gross_rent
year neighborhood
2010 Alamo Square                     291.182945      1239.0
     Anza Vista                       267.932583      1239.0
     Bayview                          170.098665      1239.0
     Buena Vista Park                 347.394919      1239.0
     Central Richmond                 319.027623      1239.0
...                                          ...         ...
2016 Telegraph Hill                   903.049771      4390.0
     Twin Peaks                       970.085470      4390.0
     Van Ness/ Civic Center           552.602567      4390.0
     Visitacion Valley                328.319007      4390.0
     Westwood Park                    631.195426      4390.0

[397 rows x 2 columns]

In [95]:
 # Use hvplot to create an interactive line plot of the average price per square foot
    
prices_by_year_by_neighborhood_new_plot = prices_by_year_by_neighborhood_new.hvplot.line(x="year",y=["sale_price_sqr_foot","gross_rent"],groupby="neighborhood",label="Sale Price Per Square Foot and Average Gross Rent - 2010-2016 - By Neighborhood").opts(yformatter='%.0f',xlabel='Year',ylabel='Gross Rent/Sale Price Per Square Foot')

prices_by_year_by_neighborhood_new_plot

:DynamicMap   [neighborhood]
   :NdOverlay   [Variable]
      :Curve   [year]   (value)

In [96]:
# Load neighborhoods coordinates data
neighborhood_locations_df = pd.read_csv(
    Path('D:/git/UTOR-VIRT-FIN-PT-05-2022-U-LOLC/Resources/neighborhoods_coordinates.csv'), 
    index_col="Neighborhood", 
    low_memory=False
)

# Review the DataFrame
neighborhood_locations_df

                          Lat         Lon
Neighborhood
Alamo Square        37.791012 -122.402100
Anza Vista          37.779598 -122.443451
Bayview             37.734670 -122.401060
Bayview Heights     37.728740 -122.410980
Bernal Heights      37.728630 -122.443050
...                       ...         ...
West Portal         37.740260 -122.463880
Western Addition    37.792980 -122.435790
Westwood Highlands  37.734700 -122.456854
Westwood Park       37.734150 -122.457000
Yerba Buena         37.792980 -122.396360

[73 rows x 2 columns]

In [97]:
# Calculate the mean values for each neighborhood using sfo_data_df dataframe

all_neighborhood_info_df = sfo_data_df.groupby("neighborhood").mean()

# Round the numbers in dataframe to 2 decimal points 

all_neighborhood_info_df = round(all_neighborhood_info_df,2)

# Review the resulting DataFrame

all_neighborhood_info_df

                       year  sale_price_sqr_foot  housing_units  gross_rent
neighborhood
Alamo Square        2013.00               366.02      378401.00     2817.29
Anza Vista          2013.33               373.38      379050.00     3031.83
Bayview             2012.00               204.59      376454.00     2318.40
Bayview Heights     2015.00               590.79      382295.00     3739.00
Bernal Heights      2013.50               576.75      379374.50     3080.33
...                     ...                  ...            ...         ...
West Portal         2012.25               498.49      376940.75     2515.50
Western Addition    2012.50               307.56      377427.50     2555.17
Westwood Highlands  2012.00               533.70      376454.00     2250.50
Westwood Park       2015.00               687.09      382295.00     3959.00
Yerba Buena         2012.50               576.71      377427.50     2555.17

[73 rows x 4 columns]

In [98]:
# Using the Pandas `concat` function, join the 

# neighborhood_locations_df and the all_neighborhood_info_df DataFrame

# The axis of the concatenation is "columns".

# The concat function will automatially combine columns with

# identical information, while keeping the additional columns.

all_neighborhoods_df = pd.concat(
    
    [neighborhood_locations_df, all_neighborhood_info_df], 
    
    axis="columns",
    
    sort=False
    
)

# Review the resulting DataFrame

all_neighborhoods_df

,Lat,Lon,year,sale_price_sqr_foot,housing_units,gross_rent
Alamo Square,37.791012,-122.402100,2013.00,366.02,378401.0,2817.29
Anza Vista,37.779598,-122.443451,2013.33,373.38,379050.0,3031.83
Bayview,37.734670,-122.401060,2012.00,204.59,376454.0,2318.40
Bayview Heights,37.728740,-122.410980,2015.00,590.79,382295.0,3739.00
Bernal Heights,37.728630,-122.443050,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
Yerba Buena,37.792980,-122.396360,2012.50,576.71,377427.5,2555.17
Bernal Heights,NaN,NaN,2013.50,576.75,379374.5,3080.33
Downtown,NaN,NaN,2013.00,391.43,378401.0,2817.29
Ingleside,NaN,NaN,2012.50,367.90,377427.5,2509.00
Outer Richmond,NaN,NaN,2013.00,473.90,378401.0,2817.29

In [99]:
# Call the dropna function to remove any neighborhoods that do not have data

all_neighborhoods_df = all_neighborhoods_df.reset_index().dropna()

In [100]:
# Rename the "index" column as "Neighborhood" for use in the Visualization

all_neighborhoods_df = all_neighborhoods_df.rename(columns={"index": "Neighborhood"})

In [101]:
# Review the resulting DataFrame
all_neighborhoods_df.head()

,Neighborhood,Lat,Lon,year,sale_price_sqr_foot,housing_units,gross_rent
0,Alamo Square,37.791012,-122.402100,2013.00,366.02,378401.0,2817.29
1,Anza Vista,37.779598,-122.443451,2013.33,373.38,379050.0,3031.83
2,Bayview,37.734670,-122.401060,2012.00,204.59,376454.0,2318.40
3,Bayview Heights,37.728740,-122.410980,2015.00,590.79,382295.0,3739.00
5,Buena Vista Park,37.768160,-122.439330,2012.83,452.68,378076.5,2698.83

In [ ]:
--